spring.data.mongodb.uri=mongodb://localhost:27017/boomerang

mongock.enabled=true
mongock.runner-type=applicationrunner
mongock.lock-repository-name=sys_lock_bosun
mongock.migration-repository-name=sys_changelog_bosun
mongock.migration-scan-package=net.boomerangplatform.migration.changesets.bosun